apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      nodeSelector:
        kubernetes.io/hostname: pavan-vps
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: qbittorrent-config
        hostPath:
          path: /mnt/data/media/qbittorrent-config
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: /mnt/data/media/downloads
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: qbittorrent
