---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: pavan-vps
    path: /mnt/data/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: nas
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: media-nfs-pv
